# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CopernicusData
                                 A QGIS plugin
 This plugin downloads data using the cdsapi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-21
        copyright            : (C) 2020 by Fredrik Lindberg
        email                : fredrikl@gvc.gu.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CopernicusData class from file CopernicusData.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .copernicus_data import CopernicusData
    return CopernicusData(iface)
