# -*- coding: utf-8 -*-
"""
/***************************************************************************
 uwg_reclassifier
                                 A QGIS plugin
 This Plugin reclassifies vector data into UWG Classes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-11
        copyright            : (C) 2021 by Oskar Bäcklin & Fredrik Lindberg University of Gothenburg
        email                : oskar.backlin@gu.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load uwg_reclassifier class from file uwg_reclassifier.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .uwg_reclassifier import uwg_reclassifier
    return uwg_reclassifier(iface)
