# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UWGPrepare
                                 A QGIS plugin
 Prepares input data to UWG
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-18
        copyright            : (C) 2021 by Fredrik Lindberg
        email                : fredrikl@gvc.gu.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UWGPrepare class from file UWGPrepare.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .uwg_prepare import UWGPrepare
    return UWGPrepare(iface)
