# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SUEWSConverter
                                 A QGIS plugin
 Converts SUEWS input data between versions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-06
        copyright            : (C) 2019 by Fredrik Lindberg
        email                : fredrikl@gvc.gu.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SUEWSConverter class from file SUEWSConverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .suews_converter import SUEWSConverter
    return SUEWSConverter(iface)
